"use client";

import { useState } from "react";
import type { Weights, AnalystMemo as Memo } from "@/lib/types";

function memoToMarkdown(m: Memo): string {
  return [
    `# ${m.ticker} — Analyst Memo`,
    ``,
    `**Thesis.** ${m.thesis}`,
    ``,
    `## Bull`,
    ...m.bull.map((b) => `- ${b}`),
    ``,
    `## Bear`,
    ...m.bear.map((b) => `- ${b}`),
    ``,
    `## Score reconciliation`,
    m.scoreReconciliation,
    ``,
    `## What would change it`,
    ...m.whatWouldChangeIt.map((b) => `- ${b}`),
    ``,
    `## Verdict`,
    m.verdict,
    ``,
    `_Generated by ${m.model}. Not investment advice._`,
  ].join("\n");
}

export function AnalystMemo({ ticker, weights }: { ticker: string; weights: Weights }) {
  const [memo, setMemo] = useState<Memo | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  async function generate() {
    setLoading(true);
    setError(null);
    setMemo(null);
    try {
      const res = await fetch("/api/analyze", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ ticker, weights }),
      });
      const data = await res.json();
      if (!res.ok) setError(data.error ?? "Failed to generate memo.");
      else setMemo(data as Memo);
    } catch {
      setError("Network error reaching the analyst endpoint.");
    } finally {
      setLoading(false);
    }
  }

  function copy() {
    if (!memo) return;
    navigator.clipboard.writeText(memoToMarkdown(memo)).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    });
  }

  return (
    <div className="mt-7 rounded-lg border border-hair-strong bg-paper-raised p-5">
      <div className="flex items-center justify-between">
        <div className="font-mono text-[11px] uppercase tracking-[0.18em] text-ink-soft">
          AI Analyst Memo
        </div>
        {memo && (
          <button
            onClick={copy}
            className="font-mono text-[12px] text-ink-soft underline-offset-2 hover:underline"
          >
            {copied ? "Copied ✓" : "Copy as Markdown"}
          </button>
        )}
      </div>

      {!memo && !loading && (
        <div className="mt-3">
          <p className="font-body text-[14px] leading-relaxed text-ink-soft">
            Generate a grounded bull/bear read that reconciles the qualitative
            story with the {ticker} composite score.
          </p>
          <button
            onClick={generate}
            className="font-body mt-3 rounded-md bg-ink px-5 py-2.5 text-[14px] font-semibold text-paper transition-opacity hover:opacity-85"
          >
            Generate memo
          </button>
        </div>
      )}

      {loading && (
        <div className="mt-4 font-mono text-[13px] text-ink-soft">
          Drafting memo…
        </div>
      )}

      {error && (
        <div className="mt-3 rounded-md border border-avoid/40 bg-[var(--avoid-soft)] px-3 py-2 font-body text-[13px] text-avoid">
          {error}
        </div>
      )}

      {memo && (
        <div className="mt-4 space-y-5">
          <p className="font-display text-lg leading-snug text-ink">{memo.thesis}</p>

          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            <div>
              <div className="font-mono mb-1.5 text-[11px] uppercase tracking-wider text-good">
                Bull
              </div>
              <ul className="space-y-1.5">
                {memo.bull.map((b, i) => (
                  <li key={i} className="font-body text-[13.5px] leading-snug text-ink">
                    {b}
                  </li>
                ))}
              </ul>
            </div>
            <div>
              <div className="font-mono mb-1.5 text-[11px] uppercase tracking-wider text-avoid">
                Bear
              </div>
              <ul className="space-y-1.5">
                {memo.bear.map((b, i) => (
                  <li key={i} className="font-body text-[13.5px] leading-snug text-ink">
                    {b}
                  </li>
                ))}
              </ul>
            </div>
          </div>

          <div>
            <div className="font-mono mb-1 text-[11px] uppercase tracking-wider text-ink-soft">
              Score reconciliation
            </div>
            <p className="font-body text-[13.5px] leading-relaxed text-ink">
              {memo.scoreReconciliation}
            </p>
          </div>

          <div>
            <div className="font-mono mb-1 text-[11px] uppercase tracking-wider text-ink-soft">
              What would change it
            </div>
            <ul className="space-y-1">
              {memo.whatWouldChangeIt.map((b, i) => (
                <li key={i} className="font-body text-[13.5px] leading-snug text-ink">
                  → {b}
                </li>
              ))}
            </ul>
          </div>

          <div className="border-t border-hair pt-3">
            <div className="font-mono mb-1 text-[11px] uppercase tracking-wider text-ink-soft">
              Verdict
            </div>
            <p className="font-display text-[16px] leading-snug text-ink">{memo.verdict}</p>
            <p className="mt-2 font-mono text-[10px] text-ink-soft">{memo.model}</p>
          </div>
        </div>
      )}
    </div>
  );
}
